package com.classapp.schedule.util

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.compositeOver
import androidx.compose.ui.graphics.luminance
import kotlin.math.abs

object CourseColors {

    /**
     * Generate Monet-derived course colors from the current MaterialTheme colorScheme.
     * Returns a list of 8 distinct, vibrant background+text color pairs.
     * Colors are generated by rotating the hue of the primary color.
     */
    @Composable
    fun getMonetColors(): List<Pair<Color, Color>> {
        val scheme = MaterialTheme.colorScheme
        // Derive from MaterialTheme tokens
        val baseColors = listOf(
            scheme.primary to scheme.onPrimary,
            scheme.secondary to scheme.onSecondary,
            scheme.tertiary to scheme.onTertiary,
            scheme.error to scheme.onError,
            scheme.primaryContainer to scheme.onPrimaryContainer,
            scheme.secondaryContainer to scheme.onSecondaryContainer,
            scheme.tertiaryContainer to scheme.onTertiaryContainer,
            scheme.inversePrimary to scheme.inverseSurface,
        )
        // Lighten/darken for variety
        return baseColors.map { (bg, fg) ->
            // Use a lighter variant for course blocks
            val lightBg = bg.copy(alpha = 0.15f).compositeOver(scheme.surface)
            lightBg to bg
        }
    }

    /**
     * Get a color pair for a specific course index (0-based).
     * Assigns unique colors without repetition.
     */
    @Composable
    fun getCourseColor(index: Int): Pair<Color, Color> {
        val colors = getMonetColors()
        val i = index.coerceIn(0, colors.size - 1)
        return colors[i]
    }

    /**
     * Get background color for a course (theme-aware, Monet-derived)
     */
    @Composable
    fun getBackground(index: Int): Color {
        return getCourseColor(index).first
    }

    /**
     * Get text color for a course (theme-aware, Monet-derived)
     */
    @Composable
    fun getTextColor(index: Int): Color {
        return getCourseColor(index).second
    }

    /**
     * Non-composable version using pre-computed colors
     */
    fun getBackground(index: Int, monetColors: List<Pair<Color, Color>>): Color {
        return monetColors[index.coerceIn(0, monetColors.size - 1)].first
    }

    fun getTextColor(index: Int, monetColors: List<Pair<Color, Color>>): Color {
        return monetColors[index.coerceIn(0, monetColors.size - 1)].second
    }

    /**
     * Assign unique color indices to courses based on course name.
     * Courses with different names get different colors.
     */
    fun assignColorIndices(courses: List<com.classapp.schedule.data.Course>): Map<Long, Int> {
        val nameToIndex = mutableMapOf<String, Int>()
        var nextIndex = 0
        return courses.associate { course ->
            val idx = nameToIndex.getOrPut(course.name) { nextIndex++ }
            course.id to (idx % 8)
        }
    }
}
